### ISSUE TITLE
When building 'pixi.js' docs I encounted 'Error: EISDIR: illegal operation on a directory'

### ISSUE THREAD

**Issue by fosonmeng** [davidshimjs/jaguarjs-jsdoc#48]
Here is my environment and the issue details
```
2 info using npm@5.6.0
3 info using node@v8.6.0

> pixi.js@3.0.11 docs /mnt/c/Users/Administrator/Workspace/github_pkgs/pixi.js-3
> jsdoc -c ./gulp/util/jsdoc.conf.json -R README.md

fs.js:1919
  binding.copyFile(src, dest, flags);
          ^

Error: EISDIR: illegal operation on a directory, copyfile '/mnt/c/Users/Administrator/Workspace/github_pkgs/pixi.js-3/node_modules/jaguarjs-jsdoc/static/fonts/glyphicons-halflings-regular.eot' -> 'docs/fonts'
    at Object.fs.copyFileSync (fs.js:1919:11)
    at /mnt/c/Users/Administrator/Workspace/github_pkgs/pixi.js-3/node_modules/jaguarjs-jsdoc/publish.js:347:12
    at Array.forEach (<anonymous>)
    at Object.exports.publish (/mnt/c/Users/Administrator/Workspace/github_pkgs/pixi.js-3/node_modules/jaguarjs-jsdoc/publish.js:344:17)
    at Object.module.exports.cli.generateDocs (/mnt/c/Users/Administrator/Workspace/github_pkgs/pixi.js-3/node_modules/jsdoc/cli.js:430:39)
    at Object.module.exports.cli.processParseResults (/mnt/c/Users/Administrator/Workspace/github_pkgs/pixi.js-3/node_modules/jsdoc/cli.js:383:20)
    at module.exports.cli.main (/mnt/c/Users/Administrator/Workspace/github_pkgs/pixi.js-3/node_modules/jsdoc/cli.js:227:14)
    at Object.module.exports.cli.runCommand (/mnt/c/Users/Administrator/Workspace/github_pkgs/pixi.js-3/node_modules/jsdoc/cli.js:180:5)
    at /mnt/c/Users/Administrator/Workspace/github_pkgs/pixi.js-3/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/mnt/c/Users/Administrator/Workspace/github_pkgs/pixi.js-3/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
```

**Comment by fosonmeng** [comment]
I modified here and it worked
```
node_modules/jaguarjs-jsdoc/publish.js:344:17

fs.copyFileSync(fileName, path.resolve(toDir, path.basename(fileName)));
```
