### ISSUE TITLE
Using --tutorials or -u fails with jaguar template, although jsdoc is working fine default and other template

### ISSUE THREAD

**Issue by harshkurra** [davidshimjs/jaguarjs-jsdoc#49]
undefined:25
            if (item.members.length) {
                             ^

TypeError: Cannot read property 'length' of undefined
    at eval (eval at _.template (C:\DATA\JSdoc\node_modules\underscore\underscore.js:1454:20), <anonymous>:25:30)
    at Array.forEach (<anonymous>)
    at exports.Template.eval (eval at _.template (C:\DATA\JSdoc\node_modules\underscore\underscore.js:1454:20), <anonymous>:13:14)
    at exports.Template.template (C:\DATA\JSdoc\node_modules\underscore\underscore.js:1461:21)
    at exports.Template.partial (C:\DATA\JSdoc\node_modules\jsdoc\lib\jsdoc\template.js:55:29)
    at exports.Template.eval (eval at _.template (C:\DATA\JSdoc\node_modules\underscore\underscore.js:1454:20), <anonymous>:54:14)
    at exports.Template.template (C:\DATA\JSdoc\node_modules\underscore\underscore.js:1461:21)
    at exports.Template.partial (C:\DATA\JSdoc\node_modules\jsdoc\lib\jsdoc\template.js:55:29)
    at exports.Template.render (C:\DATA\JSdoc\node_modules\jsdoc\lib\jsdoc\template.js:74:24)
    at generate (C:\DATA\JSdoc\node_modules\jaguarjs-jsdoc\publish.js:128:21)
    at Object.exports.publish (C:\DATA\JSdoc\node_modules\jaguarjs-jsdoc\publish.js:471:35)
    at Object.module.exports.cli.generateDocs (C:\DATA\JSdoc\node_modules\jsdoc\cli.js:448:35)
    at Object.module.exports.cli.processParseResults (C:\DATA\JSdoc\node_modules\jsdoc\cli.js:399:20)
    at module.exports.cli.main (C:\DATA\JSdoc\node_modules\jsdoc\cli.js:240:14)
    at Object.module.exports.cli.runCommand (C:\DATA\JSdoc\node_modules\jsdoc\cli.js:189:5)
    at C:\DATA\JSdoc\node_modules\jsdoc\jsdoc.js:105:9

**Comment by chenweiyi** [comment]
I had this problem too.
Can you solve this problem?
